green_branch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
		path('users/', include('users.urls', namespace='users')),
	path('', include('green_branchs.urls', namespace='green_branchs')),
]

# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

green_branchs/urls.py
"""Определяет схемы URL для green_branchs."""

from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'green_branchs'
urlpatterns = [
	# Домашняя страница.
	path('', views.index, name='index'),

	# Вывод всех тем для планов питания.
	path(r'^topics_plan/$', views.topics_plan, name='topics_plan'),
	# Страница с подробной информацией по отдельному плану питания
	path(r'^topics_plan/(?P<topic_plan_id>\d+)/$', views.topic_plan, name='topic_plan'),

	# Вывод всех тем рецептов.
	path(r'^topics_rec/$', views.topics_rec, name='topics_rec'),
	# Страница со списком рецептов.
	path(r'^topics_rec/(?P<topic_rec_id>\d+)/$', views.topic_rec, name='topic_rec'),
	
	# Вывод всех тем продуктов.
	path(r'^topics_prod/$', views.topics_prod, name='topics_prod'),
	# Страница со списком продутов.
	path(r'^topics_prod/(?P<topic_prod_id>\d+)/$', views.topic_prod, name='topic_prod'),
	
	# Вывод всех тем для тренировок.
	path(r'^topics_activ/$', views.topics_activ, name='topics_activ'),
	# Страница со списком тренировок.
	path(r'^topics_activ/(?P<topic_activ_id>\d+)/$', views.topic_activ, name='topic_activ'),
	
	# Вывод всех тем.
	path(r'^topics/$', views.topics, name='topics'),
	# Страница с подробной информацией по отдельной теме
	path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
	# Страница для добавления новой темы
	path(r'^new_topic/$', views.new_topic, name='new_topic'),
	# Страница для добавления новой записи
	path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
	# Страница для редактирования записи
	path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,name='edit_entry'),
	
]
# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path
#from django.contrib.auth.views import login
#from django.contrib.auth import login
from django.contrib.auth import views as auth_views
#from django.contrib.auth import views as auth_views, login
from . import views

app_name = 'users'
urlpatterns = [
	# Страница входа
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
		# Страница выхода
		path('logout/', auth_views.LogoutView.as_view(), name='logout'),
		#path(r'^logout/$', views.logout_view, name='logout'),
		# Страница регистрации
		path(r'^register/$', views.register, name='register'),
		
		
]

green_branchs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic_plan(models.Model):
	#"""Тема готовых планов питания"""
	text = models.CharField(max_length=200)
	cover = models.ImageField(upload_to='images/')
	def __str__(self):
		#"""Возвращает строковое представление модели."""
		return self.text

class Entry_plan(models.Model):
	#"""Планы питания"""
	topic = models.ForeignKey(Topic_plan, on_delete = models.CASCADE)
	cover = models.ImageField(upload_to='images/')
	text = models.TextField()
	
	class Meta:
		verbose_name_plural = 'entries_plan'
	def __str__(self):
		#"""Возвращает строковое представление модели."""
		return self.text



class Topic_rec(models.Model):
	#"""Тема рецептов"""
	text = models.CharField(max_length=200)
	cover = models.ImageField(upload_to='images/')
	def __str__(self):
		#"""Возвращает строковое представление модели."""
		return self.text

class Entry_rec(models.Model):
	#"""Рецепты"""
	topic = models.ForeignKey(Topic_rec, on_delete = models.CASCADE)
	cover = models.ImageField(upload_to='images/')
	text = models.TextField()
	
	class Meta:
		verbose_name_plural = 'entries_rec'
	def __str__(self):
		#"""Возвращает строковое представление модели."""
		return self.text



class Topic_prod(models.Model):
	#"""Тема продуктов"""
	text = models.CharField(max_length=200)
	cover = models.ImageField(upload_to='images/')
	def __str__(self):
		#"""Возвращает строковое представление модели."""
		return self.text

class Entry_prod(models.Model):
	#"""Продукты"""
	topic = models.ForeignKey(Topic_prod, on_delete = models.CASCADE)
	cover = models.ImageField(upload_to='images/')
	text = models.TextField()
	
	class Meta:
		verbose_name_plural = 'entries_prod'
	def __str__(self):
		#"""Возвращает строковое представление модели."""
		return self.text



class Topic_activ(models.Model):
	#"""Тема тренировок"""
	text = models.CharField(max_length=200)
	cover = models.ImageField(upload_to='images/')
	def __str__(self):
		#"""Возвращает строковое представление модели."""
		return self.text

class Entry_activ(models.Model):
	#"""Тренировки"""
	topic = models.ForeignKey(Topic_activ, on_delete = models.CASCADE)
	cover = models.ImageField(upload_to='images/')
	text = models.TextField()
	
	class Meta:
		verbose_name_plural = 'entries_activ'
	def __str__(self):
		#"""Возвращает строковое представление модели."""
		return self.text

class Topic(models.Model):
	#"""Тема, которую изучает пользователь"""
	text = models.CharField(max_length=200)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	def __str__(self):
	#"""Возвращает строковое представление модели."""
		return self.text
#	@transaction.commit_on_success
#    def save(self, *args, **kwargs):
#       if not self.entry_id:
#            self.entry_id, _ = Entry.objects.get_or_create(text='_course_' + self.id)
#
#        super(Topic, self).save(*args, **kwargs)

class Entry(models.Model):
	topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
	text = models.TextField()
	
	class Meta:
		verbose_name_plural = 'entries'
	def __str__(self):
		return self.text[:50] + "..."

green_branchs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}
class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

green_branchs/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic_plan, Topic_rec, Topic_prod, Topic_activ, Topic, Entry
from .forms import TopicForm, EntryForm



def index(request):
#"""Домашняя страница приложения green_branchs"""
	return render(request, 'green_branchs/index.html')



def topics_plan(request):
#"""Выводит список планов питания."""	
	topics_plan = Topic_plan.objects.order_by()
	context = {'topics_plan': topics_plan}
	return render(request, 'green_branchs/topics_plan.html', context)
	
def topic_plan(request, topic_plan_id):
#"""Выводит план питания и связанные сним записи."""
	topic_plan = Topic_plan.objects.get(id=topic_plan_id)
	entries_plan = topic_plan.entry_plan_set.order_by()
	context = {'topic_plan': topic_plan, 'entries_plan': entries_plan}
	return render(request, 'green_branchs/topic_plan.html', context)
	


def topics_rec(request):
#"""Выводит список категорий рецептов."""	
	topics_rec = Topic_rec.objects.order_by()
	context = {'topics_rec': topics_rec}
	return render(request, 'green_branchs/topics_rec.html', context)
	
def topic_rec(request, topic_rec_id):
#"""Выводит список рецептов."""
	topic_rec = Topic_rec.objects.get(id=topic_rec_id)
	entries_rec = topic_rec.entry_rec_set.order_by()
	context = {'topic_rec': topic_rec, 'entries_rec': entries_rec}
	return render(request, 'green_branchs/topic_rec.html', context)



def topics_prod(request):
#"""Выводит список категорий продуктов."""	
	topics_prod = Topic_prod.objects.order_by()
	context = {'topics_prod': topics_prod}
	return render(request, 'green_branchs/topics_prod.html', context)
	
def topic_prod(request, topic_prod_id):
#"""Выводит список продуктов."""
	topic_prod = Topic_prod.objects.get(id=topic_prod_id)
	entries_prod = topic_prod.entry_prod_set.order_by()
	context = {'topic_prod': topic_prod, 'entries_prod': entries_prod}
	return render(request, 'green_branchs/topic_prod.html', context)



def topics_activ(request):
#"""Выводит список категорий тренировок."""	
	topics_activ = Topic_activ.objects.order_by()
	context = {'topics_activ': topics_activ}
	return render(request, 'green_branchs/topics_activ.html', context)
	
def topic_activ(request, topic_activ_id):
#"""Выводит список тренировок."""
	topic_activ = Topic_activ.objects.get(id=topic_activ_id)
	entries_activ = topic_activ.entry_activ_set.order_by()
	context = {'topic_activ': topic_activ, 'entries_activ': entries_activ}
	return render(request, 'green_branchs/topic_activ.html', context)



@login_required
def topics(request):
#"""Выводит список тем."""	
	topics = Topic.objects.filter(owner=request.user).order_by()
	context = {'topics': topics}
	return render(request, 'green_branchs/topics.html', context)

@login_required
def topic(request, topic_id):
#"""Выводит одну тему и все ее записи."""
	topic = Topic.objects.get(id=topic_id)
	# Проверка того, что тема принадлежит текущему пользователю.
	if topic.owner != request.user:
		raise Http404
	entries = topic.entry_set.order_by()
	context = {'topic': topic, 'entries': entries}
	return render(request, 'green_branchs/topic.html', context)

@login_required
def new_topic(request):
#"""Определяет новую тему."""
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма.
		form = TopicForm()
	else:
		# Отправлены данные POST; обработать данные.
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
#			form.save()
		return HttpResponseRedirect(reverse('green_branchs:topics'))
	context = {'form': form}
	return render(request, 'green_branchs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
#"""Добавляет новую запись по конкретной теме."""
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма.
		form = EntryForm()
	else:
		# Отправлены данные POST; обработать данные.
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('green_branchs:topic', args=[topic_id]))
	context = {'topic': topic, 'form': form}
	return render(request, 'green_branchs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
#"""Редактирует существующую запись."""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404
	if request.method != 'POST':
		# Исходный запрос; форма заполняется данными текущей записи.
		form = EntryForm(instance=entry)
	else:
		# Отправка данных POST; обработать данные.
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('green_branchs:topic', args=[topic.id]))
	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'green_branchs/edit_entry.html', context)

green_branchs/templates/green_branchs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<title>Green Branch</title>
	
	{% bootstrap_css %}
	{% bootstrap_javascript %}
  
  </head>
    <body>
	  <!-- Статическая навигационная панель -->
	  <nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			
		  <div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
			  data-toggle="collapse" data-target="#navbar"
			  aria-expanded="false" aria-controls="navbar">
			</button>
			<a class="navbar-brand" href="{% url 'green_branchs:index' %}">
			  Green Branch</a>
		  </div>
		  
		  <div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
			  <li><a href="{% url 'green_branchs:topics_plan' %}">Готовые планы питания</a></li>
			  <li><a href="{% url 'green_branchs:topics_rec' %}">Рецепты</a></li>
			  <li><a href="{% url 'green_branchs:topics_prod' %}">Продукты</a></li>
			  <li><a href="{% url 'green_branchs:topics_activ' %}">Тренировки</a></li>
			  <li><a href="{% url 'green_branchs:topics' %}">Расписание</a></li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
			  {% if user.is_authenticated %}
				<li><a>Hello, {{ user.username }}.</a></li>
				<li><a href="{% url 'users:logout' %}">Выйти</a></li>
			  {% else %}
				<li><a href="{% url 'users:register' %}">Регистрация</a></li>
				<li><a href="{% url 'users:login' %}">Войти</a></li>
			  {% endif %}
			</ul>
		  </div><!--/.nav-collapse -->
		
		</div>
	  </nav>
	    <div class="container">
		  <div class="page-header">
			{% block header %}{% endblock header %}
		  </div>
		  <div>
			{% block content %}{% endblock content %}
		  </div>
		</div> <!-- /container -->
	</body>
</html>

green_branchs/templates/green_branchs/base.org.html
<p>
<a href="{% url 'green_branchs:index' %}">Green Branch</a> -
  <a href="{% url 'green_branchs:topics_plan' %}">Готовые планы питания</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }}.
      <a href="{% url 'users:logout' %}">Выйти</a>
  {% else %}
    <a href="{% url 'users:register' %}">Регистрация</a> -
    <a href="{% url 'users:login' %}">Войти</a>
  {% endif %}
</p>
{% block content %}{% endblock content %}

green_branchs/templates/green_branchs/edit_entry.html
{% extends "green_branchs/base.html" %}

{% block content %}

  <p><a href="{% url 'green_branchs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Редактировать:</p>
  <form action="{% url 'green_branchs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Сохранить изменения</button>
  </form>
  
{% endblock content %}

green_branchs/templates/green_branchs/index.html
{% extends "green_branchs/base.html" %}

{% block header %}
  <div class='jumbotron'>
	<h1>Следите за своим образом жизни, телом и питанием.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
	<a href="{% url 'users:register' %}">Зарегистрируйте аккаунт</a> 
	чтобы создать журнал правильного питания и занятий.
  </h2>
  <h2>
	Здесь вы можете планировать свой режим питания и занятий спортом,
	выбрав из большого количества предложенных вариантов.
  </h2>
{% endblock content %}

green_branchs/templates/green_branchs/index.org.html
{% extends "green_branchs/base.html" %}

{% block content %}
<p>Ресурс для тех кто следит за своим здоровьем, телом и правильным питанием.</p>
{% endblock content %}

green_branchs/templates/green_branchs/new_entry.html
{% extends "green_branchs/base.html" %}

{% block content %}

  <p><a href="{% url 'green_branchs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Добавить новую запись:</p>
  <form action="{% url 'green_branchs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Добавить запись</button>
  </form>
  
{% endblock content %}

green_branchs/templates/green_branchs/topic.html
{% extends 'green_branchs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
<p>
<a href="{% url 'green_branchs:new_entry' topic.id %}">Добавить запись</a>
</p>

{% for entry in entries %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>
	    <!--{{ entry.date_added|date:'M d, Y H:i' }}-->
	    <small>
		  <a href="{% url 'green_branchs:edit_entry' entry.id %}"> Редактировать расписание</a>
	    </small>
	  </h3>
    </div>
    <div class="panel-body">
	  {{ entry.text|linebreaks }}
    </div>
  </div> <!-- panel -->
{% empty %}
  Записей пока нет.
{% endfor %}

{% endblock content %}

green_branchs/templates/green_branchs/topic_activ.html
{% extends 'green_branchs/base.html' %}

{% block header %}
  <h2>{{ topic_activ }}</h2>
{% endblock header %}

{% block content %}

{% for entry_activ in entries_activ %}
  <div class="panel panel-default">
    <div class="panel-body">
	  <img src="{{ entry_activ.cover.url }}">
	  {{ entry_activ.text|linebreaks }}
    </div>
  </div> <!-- panel -->
{% empty %}
  Этот раздел не описан.
{% endfor %}

{% endblock content %}

green_branchs/templates/green_branchs/topic_plan.org.html
{% extends "green_branchs/base.html" %}

{% block content %}

  <p>План питания: {{ topic_plan }}</p>
  
  <p>Подробнее:</p>
    <ul>
     {% for entry_plan in entries_plan %}
	   <li>
		  <p>{{ entry_plan.text|linebreaks }}</p>
	   </li>
	{% empty %}
	   <li>
	     Этот раздел не описан.  
	   </li>
    {% endfor %}
  </ul>
  
{% endblock content %}

green_branchs/templates/green_branchs/topic_prod.html
{% extends 'green_branchs/base.html' %}

{% block header %}
  <h2>{{ topic_prod }}</h2>
{% endblock header %}

{% block content %}

{% for entry_prod in entries_prod %}
  <div class="panel panel-default">
    <div class="panel-body">
	  <img src="{{ entry_prod.cover.url }}">
	  {{ entry_prod.text|linebreaks }}
    </div>
  </div> <!-- panel -->
{% empty %}
  Этот раздел не описан.
{% endfor %}

{% endblock content %}

green_branchs/templates/green_branchs/topic_rec.html
{% extends 'green_branchs/base.html' %}

{% block header %}
  <h2>{{ topic_rec }}</h2>
{% endblock header %}

{% block content %}

{% for entry_rec in entries_rec %}
  <div class="panel panel-default">
    <div class="panel-body">
	  <img src="{{ entry_rec.cover.url }}">
	  {{ entry_rec.text|linebreaks }}
    </div>
  </div> <!-- panel -->
{% empty %}
  Этот раздел не описан.
{% endfor %}

{% endblock content %}

green_branchs/templates/green_branchs/topics.html
{% extends "green_branchs/base.html" %}

{% block header %}
  <h1>Расписание</h1>
{% endblock header %}

{% block content %}

<ul>
{% for topic in topics %}
<li>
  <h3>
	<a href="{% url 'green_branchs:topic' topic.id %}">{{ topic }}</a>
  </h3>
</li>
{% empty %}
<li>Расписания пока нет.</li>
{% endfor %}
</ul>

  <h3><a href="{% url 'green_branchs:new_topic' %}">Добавить расписание</h3>

{% endblock content %}

green_branchs/templates/green_branchs/topics_plan.org.html
{% extends "green_branchs/base.html" %}

{% block content %}

  <p>Планы питания:</p>
  
  <ul>
    {% for topic_plan in topics_plan %}
      <li>
        <a href="{% url 'green_branchs:topic_plan' topic_plan.id %}">{{ topic_plan }}</a>
	  </li>
    {% empty %}
      <li>Диеты еще не представлены.</li>
    {% endfor %}
  </ul>
  
{% endblock content %}

green_branchs/templates/green_branchs/topics_prod.html
{% extends "green_branchs/base.html" %}

{% block header %}
  <h1>Продукты</h1>
{% endblock header %}

{% block content %}

<ul>
{% for topic_prod in topics_prod %}
  <div class="panel panel-default">
    <div class="panel-body">
	  <img src="{{ topic_prod.cover.url }}">
	  <a href="{% url 'green_branchs:topic_prod' topic_prod.id %}">{{ topic_prod }}</a>
    </div>
  </div> <!-- panel -->
{% empty %}
<li>Продуктов пока нет.</li>
{% endfor %}
</ul>

{% endblock content %}